name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # SHOW_OS: "False"
          # SHOW_PROJECTS: "False"
          # LOCALE This Flag can be used to show stats in your language default is english uses Locale Short Hand to be passed in the flag variable example of the final result can be found here
          # COMMIT_BY_ME flag can be set to True to commit the code using your name and email
          # COMMIT_MESSAGE flag can be to set message commit, default is "Updated with Dev Metrics"
          # SHOW_UPDATED_DATE flag can be set to True to show updated date in end of paragraph
          # SHOW_LINES_OF_CODE flag can be set to True to show the Lines of code writen till date
          # SHOW_PROFILE_VIEWS flag can be set to False to hide the Profile views
          # SHOW_COMMIT flag can be set to False to hide the commit stats
